runtime: python37

#api_version: 1
#threadsafe: true

#handlers:
#- url: .*
#  script: main.app

#libraries:
#- name: ssl
#  version: latest

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
